---
version: 0.2
env:
  variables:
    AWS_REGION: us-east-1
    COMMIT_HASH: trucks
    IMAGE_TAG: latest
    AWS_ACCOUNT_ID: 500208773665
phases:
  install:
    runtime-versions:
      docker: 20
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$COMMIT_HASH
  build:
    commands:
      - echo Building WAR file as on `date`
      - mvn clean package
      - echo MOVE THE WAR FILE TO S3
      - aws s3 cp $CODEBUILD_SRC_DIR/target/trucks.war s3://artifact-trucks/
  post_build:
    commands:
      - echo Building DOCKER image ....
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - echo Tagging image ...
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
      - echo Pushing IMAGE to ECR
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file... 
      - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json
      - echo Push the Latest Image to cluster ...
      # kubectl apply -f deployment.yaml
      # kubectl apply -f service.yaml
artifacts:
  files:
    - imageDetail.json
  discard-paths: yes
