---
version: 0.2
env:
  variables:
    AWS_REGION: us-east-1
    COMMIT_HASH: trucks
    IMAGE_TAG: latest
phases:
  install:
    runtime-versions:
      docker: 20
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - REPOSITORY_URI=500208773665.dkr.ecr.us-east-1.amazonaws.com/$COMMIT_HASH
  build:
    commands:
      - echo Building WAR file as on `date`
      - mvn clean package
    artifacts:
      files:
        - target/trucks.war
      discard-paths: yes
  post_build:
    commands:
      - echo Building DOCKER image ....
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - echo Tagging image ....
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
      - echo Pushing IMAGE to ECR
      # docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file... 
      - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json
artifacts:
  files:
    - imageDetail.json
