---
version: 0.2
env:
  variables:
    AWS_REGION: us-east-1
    
phases:
  install:
    runtime-versions:
      docker: 20
  pre_build:
    commands:
    - echo Building WAR file as on `date`
    - mvn clean package
    - echo Logging in to Amazon ECR...
    - aws --version
    - aws ecr get-login --region $AWS_REGION
    - COMMIT_HASH=trucks
    - IMAGE_TAG=latest
    - REPOSITORY_URI=500208773665.dkr.ecr.us-east-1.amazonaws.com/$COMMIT_HASH
  build:
    commands:
    - echo Building DOCKER image ....
    # BUILD THE IMAGE
    - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
    # TAG THE IMAGE
    - echo Tagging image ....
    - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
    - echo Pushing IMAGE to ECR
    # PUSH THE IMAGE TO ECR repository
    - docker push $REPOSITORY_URI:latest
    - docker push $REPOSITORY_URI:$IMAGE_TAG
    - echo Writing image definitions file...
artifacts:
  files:
    - target/trucks.war
  discard-paths: yes
